name: 11 Custom Actions - Composite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Use Custom Composite Action
      - name: Build Node
        uses: ./.github/actions/composite-deps
        with:
          work-dir: my-app       # Directorio de trabajo
          node-version: 20.x     # Versión de Node.js
